name: AnteHandler Benchmark Tests

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  ante-benchmark-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          PATTERNS: |
            app/ante/**.go
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
        if: env.GIT_DIFF
      - name: Run benchmark tests
        run: go test -bench=. ./app/ante/... -benchtime=1000x
        if: env.GIT_DIFF
