name: Push to Buf Schema Registry
# This workflow runs when a new version tag is pushed to the repository.
# It then pushes the Protobuf files corresponding to that tag on to the
# Buf Schema Registry at https://buf.build/evmos/evmos
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.23.1
      # Push Evmos protos to the Buf Schema Registry
      - uses: bufbuild/buf-push-action@v1.1.1
